[2025-04-21T13:14:05.332+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-21T13:14:05.374+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hourly_etl_pipeline.load_stg manual__2025-04-21T13:14:03.832155+00:00 [queued]>
[2025-04-21T13:14:05.390+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hourly_etl_pipeline.load_stg manual__2025-04-21T13:14:03.832155+00:00 [queued]>
[2025-04-21T13:14:05.391+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-04-21T13:14:05.421+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_stg> on 2025-04-21 13:14:03.832155+00:00
[2025-04-21T13:14:05.427+0000] {standard_task_runner.py:63} INFO - Started process 487 to run task
[2025-04-21T13:14:05.439+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'hourly_etl_pipeline', 'load_stg', 'manual__2025-04-21T13:14:03.832155+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/hourly_etl_pipeline.py', '--cfg-path', '/tmp/tmpfaf38yce']
[2025-04-21T13:14:05.447+0000] {standard_task_runner.py:91} INFO - Job 10: Subtask load_stg
[2025-04-21T13:14:05.643+0000] {task_command.py:426} INFO - Running <TaskInstance: hourly_etl_pipeline.load_stg manual__2025-04-21T13:14:03.832155+00:00 [running]> on host ab2b55c0754d
[2025-04-21T13:14:05.815+0000] {logging_mixin.py:188} WARNING - /root/.local/lib/python3.8/site-packages/***/utils/context.py:212 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2025-04-21T13:14:05.982+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='hourly_etl_pipeline' AIRFLOW_CTX_TASK_ID='load_stg' AIRFLOW_CTX_EXECUTION_DATE='2025-04-21T13:14:03.832155+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-21T13:14:03.832155+00:00'
[2025-04-21T13:14:05.984+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-21T13:14:06.024+0000] {logging_mixin.py:188} INFO - Target time: 2025-04-21 13:14:03.832155+00:00
[2025-04-21T13:14:06.086+0000] {base.py:84} INFO - Using connection ID 'postgresql_lab08' for task execution.
[2025-04-21T13:14:06.159+0000] {logging_mixin.py:188} INFO - Processing file: year=2025/month=04/day=21/hour=13/browser_events.jsonl.zip
[2025-04-21T13:14:06.178+0000] {base.py:84} INFO - Using connection ID 's3_yandex' for task execution.
[2025-04-21T13:14:06.185+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='s3_yandex', conn_type='aws') credentials retrieved from login and password.
[2025-04-21T13:14:30.751+0000] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to success. Terminating instance.
[2025-04-21T13:14:30.753+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-04-21T13:14:30.756+0000] {process_utils.py:132} INFO - Sending 15 to group 487. PIDs of all processes in the group: [487]
[2025-04-21T13:14:30.757+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 487
[2025-04-21T13:15:30.781+0000] {process_utils.py:150} WARNING - process psutil.Process(pid=487, name='airflow task ru', status='sleeping', started='13:14:05') did not respond to SIGTERM. Trying SIGKILL
[2025-04-21T13:15:30.783+0000] {process_utils.py:87} INFO - Sending the signal 9 to group 487
[2025-04-21T13:15:30.797+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=487, name='airflow task ru', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='13:14:05') (487) terminated with exit code -9
[2025-04-21T13:15:30.798+0000] {standard_task_runner.py:178} ERROR - Job 10 was killed before it finished (likely due to running out of memory)
